{"uuid":"ff26a2d4-6c74-4c41-ac97-0ba3cf46e785","name":"testClasses.loginTest","children":["537a3dbe-86cd-4fb5-9bbb-d5e7953ef850","ac2a451a-2de9-4f5a-98c4-238855506ebd","3a8db540-d48d-425c-926b-278ced0c6ebc"],"befores":[{"name":"setup","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The local appium server has not been started. The given Node.js executable: C:\\Program Files\\nodejs\\node.exe Arguments: [C:\\Appium\\AppiumServer\\Appium-Server-GUI-windows-1.22.3-4\\resources\\app\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --base-path, wd/hub/] \nProcess output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v1.22.3\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m   address: 127.0.0.1\r\n\u001B[35m[Appium]\u001B[39m   basePath: wd/hub/\r\n\u001B[35m[HTTP]\u001B[39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\nFatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1817:16)\n    at listenInCluster (node:net:1865:12)\n    at doListen (node:net:2014:7)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n\n","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\\Program Files\\nodejs\\node.exe Arguments: [C:\\Appium\\AppiumServer\\Appium-Server-GUI-windows-1.22.3-4\\resources\\app\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --base-path, wd/hub/] \nProcess output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v1.22.3\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m   address: 127.0.0.1\r\n\u001B[35m[Appium]\u001B[39m   basePath: wd/hub/\r\n\u001B[35m[HTTP]\u001B[39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\nFatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1817:16)\n    at listenInCluster (node:net:1865:12)\n    at doListen (node:net:2014:7)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n\n\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:182)\r\n\tat base.baseClass.setup(baseClass.java:45)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)\r\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/wd/hub/status] to be available after 20011 ms\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:147)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:169)\r\n\t... 26 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)\r\n\t... 28 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1710648779348,"stop":1710648799900},{"name":"LoginM1A","status":"passed","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1710648800530,"stop":1710648800551}],"afters":[{"name":"tearDown","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1710648800727,"stop":1710648800727}],"start":1710648778784,"stop":1710648802186}